/*
 * This file is generated by jOOQ.
 */
package com.example.eschatbot.database.tables.records;


import com.example.eschatbot.database.tables.JourneyMaster;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JourneyMasterRecord extends TableRecordImpl<JourneyMasterRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>chatbot.journey_master.journey_id</code>.
     */
    public void setJourneyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chatbot.journey_master.journey_id</code>.
     */
    public Integer getJourneyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chatbot.journey_master.journey_name</code>.
     */
    public void setJourneyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chatbot.journey_master.journey_name</code>.
     */
    public String getJourneyName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JourneyMaster.JOURNEY_MASTER.JOURNEY_ID;
    }

    @Override
    public Field<String> field2() {
        return JourneyMaster.JOURNEY_MASTER.JOURNEY_NAME;
    }

    @Override
    public Integer component1() {
        return getJourneyId();
    }

    @Override
    public String component2() {
        return getJourneyName();
    }

    @Override
    public Integer value1() {
        return getJourneyId();
    }

    @Override
    public String value2() {
        return getJourneyName();
    }

    @Override
    public JourneyMasterRecord value1(Integer value) {
        setJourneyId(value);
        return this;
    }

    @Override
    public JourneyMasterRecord value2(String value) {
        setJourneyName(value);
        return this;
    }

    @Override
    public JourneyMasterRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JourneyMasterRecord
     */
    public JourneyMasterRecord() {
        super(JourneyMaster.JOURNEY_MASTER);
    }

    /**
     * Create a detached, initialised JourneyMasterRecord
     */
    public JourneyMasterRecord(Integer journeyId, String journeyName) {
        super(JourneyMaster.JOURNEY_MASTER);

        setJourneyId(journeyId);
        setJourneyName(journeyName);
    }
}
