/*
 * This file is generated by jOOQ.
 */
package com.example.eschatbot.database;


import com.example.eschatbot.database.tables.Customerstate;
import com.example.eschatbot.database.tables.JourneyMaster;
import com.example.eschatbot.database.tables.QuestionsNext;


/**
 * Convenience access to all tables in chatbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>chatbot.customerstate</code>.
     */
    public static final Customerstate CUSTOMERSTATE = Customerstate.CUSTOMERSTATE;

    /**
     * The table <code>chatbot.journey_master</code>.
     */
    public static final JourneyMaster JOURNEY_MASTER = JourneyMaster.JOURNEY_MASTER;

    /**
     * The table <code>chatbot.questions_next</code>.
     */
    public static final QuestionsNext QUESTIONS_NEXT = QuestionsNext.QUESTIONS_NEXT;
}
